const { Client } = require('../src/client')
const { CURRENT_VERSION } = require('../src/options')

function getTransport (version = CURRENT_VERSION) {
  return require('minecraft-data')('bedrock_' + version).supportFeature('defaultTransportIsNethernet') ? 'nethernet' : 'raknet'
}

function createVanillaClient (options) {
  const transport = options.transport ?? getTransport(options.version)
  if (transport === 'nethernet' && !options.offline) throw new Error('Vanilla HTTP test clients require offline mode')
  // Trust the key generated by our local test server; signatures are still verified.
  const nethernet = { signalling: 'http', onServerKey: () => true, ...options.nethernet }
  return new Client({ ...options, transport, nethernet })
}

module.exports = { createVanillaClient, getTransport }
