name: Update Helper
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

concurrency:
  group: update-helper
  cancel-in-progress: false

jobs:
  helper:
    name: update-checker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 22.0.0
    - name: Install Github Actions helper
      run: npm i --no-save gh-helpers minecraft-bedrock-server@^1.7.0 minecraft-data
    # The env vars contain the relevant trigger information, so we don't need to pass it
    - name: Runs helper
      run: cd .github/helper-bot && node index.js
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_PASSWORD }}
