name: Update Helper
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  helper:
    name: update-checker
    runs-on: ubuntu-latest
    outputs:
      updateVersion: ${{ steps.helperRun.outputs.updateVersion }}
      issueNumber: ${{ steps.helperRun.outputs.issueNumber }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 20.0.0
    - name: Install deps in helper-bot
      run: npm install
      working-directory: .github/helper-bot
    # The env vars contain the relevant trigger information, so we don't need to pass it
    - name: Runs helper
      id: helperRun
      run: node index.js
      working-directory: .github/helper-bot
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_PASSWORD }}
    # Above step sets output of updateVersion, issueNumber with actions/core

  update:
    name: Update
    needs: helper
    runs-on: ubuntu-latest
    # run if updateVersion exists
    if: ${{ needs.helper.outputs.updateVersion }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 20.0.0
    - name: Compile disa
      run: clang++ -std=c++20 -O3 -o disa.exe disa.cpp
      working-directory: .github/helper-bot
    - name: Compile pdba
      run: clang++-14 -g `llvm-config-14 --cxxflags --ldflags --libs` -o pdba.exe pdba.cpp
      working-directory: .github/helper-bot
    - name: Install bedrock-protocol
      run: npm install gh-helpers
    # This step sets the "serverVersion" and "serverPath" outputs
    # Note, sometimes the serverVersionStr != clientVersionStr, so we handle that too via protocol check
    - name: Update Step 1
      id: update1Run
      run: cd .github/helper-bot && node update1.js
      # Pass the output from the helper job to the update job
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_PASSWORD }}
        UPDATE_VERSION: ${{ needs.helper.outputs.updateVersion }}
        ISSUE_NUMBER: ${{ needs.helper.outputs.issueNumber }}
    # The above will return a "needsUpdate" output.
    - name: Dump .rodata
      if: steps.update1Run.outputs.needsUpdate
      run: objcopy -O binary -j .rodata ${{ steps.update1Run.outputs.serverBin }} .github/helper-bot/rodata.bin
    - run: sha1sum ${{ steps.update1Run.outputs.serverBin }}
    - run: llvm-objdump-14 -d --demangle --no-show-raw-insn ${{ steps.update1Run.outputs.serverBin }} > llvm.asm
    - run: head -n 20 llvm.asm
    - name: Process Linux server (Stage 1)
      if: steps.update1Run.outputs.needsUpdate
      run: llvm-objdump-14 -d --demangle --no-show-raw-insn ${{ steps.update1Run.outputs.serverBin }} | .github/helper-bot/disa.exe -s1 .github/helper-bot/rodata.bin > .github/helper-bot/stage1.txt
    - name: Process Windows bin (Stage 2)
      if: steps.update1Run.outputs.needsUpdate
      run: objdump -d --demangle -M intel ${{ steps.update1Run.outputs.serverWinBin }} | .github/helper-bot/disa.exe -s2 .github/helper-bot/stage1.txt > .github/helper-bot/stage2.txt
    - name: Resolve numbers (Stage 3)
      if: steps.update1Run.outputs.needsUpdate
      run : node update2.js -s3
      working-directory: .github/helper-bot
    - name: Resolve PDB symbols (Stage 4)
      if: steps.update1Run.outputs.needsUpdate
      run: llvm-pdbutil-14 dump --all ${{ steps.update1Run.outputs.serverWinPdb }} | .github/helper-bot/pdba.exe > .github/helper-bot/stage4.txt
    # We use Artifacts API for cross repo com which is only avaliable within an Action, but not normal run jobs.
    # So we need to store the keys in the env for update3 to use to do a workflow dispatch
    # as in https://github.com/extremeheat/gh-helpers/blob/main/.github/workflows/ci.yml
    - name: Expose GitHub Runtime
      if: steps.update1Run.outputs.needsUpdate
      uses: crazy-max/ghaction-github-runtime@v3
    - name: Aggregate and finish
      if: steps.update1Run.outputs.needsUpdate
      run: node update3.js
      working-directory: .github/helper-bot
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_PASSWORD }}
        UPDATE_VERSION: ${{ needs.helper.outputs.updateVersion }}
        SERVER_VERSION: ${{ steps.update1Run.outputs.serverVersion }}
        PROTOCOL_VERSION: ${{ steps.update1Run.outputs.protocolVersion }}
        ISSUE_NUMBER: ${{ needs.helper.outputs.issueNumber }}